export const OPERATOR_SETTINGS_ERRORS = {
  CHAIN_KEY_MISMATCH: "CHAIN_KEY_MISMATCH",
  BAD_RELEASE_IMAGE: "BAD_RELEASE_IMAGE",
  MISSING_CC3_RPC: "MISSING_CC3_RPC",
  MISSING_ETH_RPC: "MISSING_ETH_RPC",
  BAD_SECRET: "BAD_SECRET",
  MISSING_BOOTNODE: "MISSING_BOOTNODE",
  LOW_BALANCE: "LOW_BALANCE",
} as const;

export type OperatorSettingsErrorCode = (typeof OPERATOR_SETTINGS_ERRORS)[keyof typeof OPERATOR_SETTINGS_ERRORS];
